#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH="$(python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

resolve_skill_root() {
  local candidates=(
    "$(cd "$SCRIPT_DIR/.." && pwd)"
    "$REPO_ROOT"
    "$HOME/.openclaw/skills/wtt"
    "$HOME/.openclaw/skills/wtt-skill"
    "$HOME/.openclaw/workspace/skills/wtt-skill"
  )
  local c
  for c in "${candidates[@]}"; do
    if [[ -f "$c/start_wtt_autopoll.py" ]]; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

SKILL_ROOT="$(resolve_skill_root || true)"
if [[ -z "$SKILL_ROOT" ]]; then
  echo "❌ start_wtt_autopoll.py not found. Checked:"
  echo "   - $(cd "$SCRIPT_DIR/.." && pwd)"
  echo "   - $REPO_ROOT"
  echo "   - $HOME/.openclaw/skills/wtt"
  echo "   - $HOME/.openclaw/skills/wtt-skill"
  echo "   - $HOME/.openclaw/workspace/skills/wtt-skill"
  exit 1
fi

START_SCRIPT="$SKILL_ROOT/start_wtt_autopoll.py"
WORKDIR="$SKILL_ROOT"
WRAPPER_SCRIPT="$SKILL_ROOT/run_autopoll.sh"

# Resolve runtime python: explicit override > skill-local venv > create skill-local venv > python3
PY_BIN="${PY_BIN:-}"
if [[ -z "$PY_BIN" ]]; then
  if [[ -x "$SKILL_ROOT/.venv/bin/python" ]]; then
    PY_BIN="$SKILL_ROOT/.venv/bin/python"
  else
    BASE_PY="$(command -v python3 || true)"
    if [[ -n "$BASE_PY" ]]; then
      if "$BASE_PY" -m venv "$SKILL_ROOT/.venv" >/dev/null 2>&1; then
        PY_BIN="$SKILL_ROOT/.venv/bin/python"
      else
        PY_BIN="$BASE_PY"
      fi
    fi
  fi
fi

if [[ -z "$PY_BIN" || ! -x "$PY_BIN" ]]; then
  echo "❌ python executable not found (set PY_BIN=... to override)"
  exit 1
fi

OPENCLAW_BIN="${OPENCLAW_BIN:-$(command -v openclaw || true)}"
SERVICE_PATH="${PATH:-/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin}"
ENV_FILE="$SKILL_ROOT/.env"
if [[ -z "$OPENCLAW_BIN" ]]; then
  OPENCLAW_BIN="openclaw"
fi

ensure_python_deps() {
  if [[ "${WTT_SKIP_PIP_INSTALL:-0}" == "1" ]]; then
    echo "ℹ️  Skip python dependency install (WTT_SKIP_PIP_INSTALL=1)"
    return 0
  fi

  if ! "$PY_BIN" -m pip --version >/dev/null 2>&1; then
    "$PY_BIN" -m ensurepip --upgrade >/dev/null 2>&1 || true
  fi

  if ! "$PY_BIN" -m pip --version >/dev/null 2>&1; then
    echo "⚠️  pip is unavailable for $PY_BIN; skip dependency install"
    return 0
  fi

  local missing
  missing="$($PY_BIN - <<'PY'
import importlib.util
mods = ["httpx", "websockets", "dotenv", "socksio"]
print(" ".join([m for m in mods if importlib.util.find_spec(m) is None]))
PY
)"

  if [[ -z "${missing// }" ]]; then
    echo "✅ Python runtime deps already present (httpx, websockets, python-dotenv, socksio)"
    return 0
  fi

  local pip_args=("--disable-pip-version-check")
  if [[ "$PY_BIN" != "$SKILL_ROOT/.venv/bin/python" ]] && [[ -z "${VIRTUAL_ENV:-}" ]]; then
    pip_args+=("--user")
  fi

  echo "ℹ️  Installing python deps for wtt-skill: $missing"
  "$PY_BIN" -m pip install "${pip_args[@]}" \
    "httpx>=0.24" \
    "websockets>=11" \
    "python-dotenv>=1" \
    "socksio>=1"
  echo "✅ Python deps installed"
}

ensure_wrapper_script() {
  if [[ ! -f "$WRAPPER_SCRIPT" ]]; then
    cat > "$WRAPPER_SCRIPT" <<'SH'
#!/usr/bin/env bash
set -euo pipefail

SKILL_DIR="${WTT_SKILL_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
cd "$SKILL_DIR"

choose_py() {
  local c
  if [[ -n "${WTT_PY_BIN:-}" ]] && [[ -x "${WTT_PY_BIN}" ]]; then
    echo "${WTT_PY_BIN}"
    return 0
  fi

  local candidates=(
    "$SKILL_DIR/.venv/bin/python"
    "$SKILL_DIR/.venv311/bin/python"
    "$HOME/.openclaw/workspace/skills/.venv311/bin/python"
  )

  for c in "${candidates[@]}"; do
    if [[ -x "$c" ]]; then
      echo "$c"
      return 0
    fi
  done

  command -v python3
}

PY="$(choose_py)"
if [[ -z "$PY" || ! -x "$PY" ]]; then
  echo "❌ No runnable python found for wtt autopoll"
  exit 1
fi

exec "$PY" "$SKILL_DIR/start_wtt_autopoll.py"
SH
  fi

  chmod +x "$WRAPPER_SCRIPT"
}

init_env_file() {
  local existing_id=""
  local agent_id=""
  local target="${WTT_IM_TARGET:-}"

  mkdir -p "$(dirname "$ENV_FILE")"

  if [[ -f "$ENV_FILE" ]]; then
    existing_id="$(grep '^WTT_AGENT_ID=' "$ENV_FILE" | tail -n1 | cut -d'=' -f2- | tr -d '\n\r' || true)"
  fi

  if [[ -n "${WTT_AGENT_ID:-}" ]]; then
    agent_id="$WTT_AGENT_ID"
  elif [[ -n "$existing_id" ]]; then
    agent_id="$existing_id"
  else
    agent_id="$(python3 - <<'PY'
import time
print(str(10_000_000 + int(time.time()*1000) % 90_000_000))
PY
)"
  fi

  if [[ ! -f "$ENV_FILE" ]]; then
    cat > "$ENV_FILE" <<EOF
# Auto-generated by install_autopoll.sh
WTT_AGENT_ID=$agent_id
WTT_IM_TARGET=$target
WTT_IM_CHANNEL=telegram
EOF
  else
    if grep -q '^WTT_AGENT_ID=' "$ENV_FILE"; then
      sed -i.bak "s/^WTT_AGENT_ID=.*/WTT_AGENT_ID=$agent_id/" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
    else
      printf "\nWTT_AGENT_ID=%s\n" "$agent_id" >> "$ENV_FILE"
    fi
    if ! grep -q '^WTT_IM_TARGET=' "$ENV_FILE"; then
      printf "WTT_IM_TARGET=%s\n" "$target" >> "$ENV_FILE"
    fi
    if ! grep -q '^WTT_IM_CHANNEL=' "$ENV_FILE"; then
      printf "WTT_IM_CHANNEL=telegram\n" >> "$ENV_FILE"
    fi
  fi

  echo "✅ Checked required .env keys: $ENV_FILE"
}

echo "ℹ️  REPO_ROOT:       $REPO_ROOT"
echo "ℹ️  SKILL_ROOT:      $SKILL_ROOT"
echo "ℹ️  WORKDIR:         $WORKDIR"
echo "ℹ️  START_SCRIPT:    $START_SCRIPT"
echo "ℹ️  WRAPPER_SCRIPT:  $WRAPPER_SCRIPT"
echo "ℹ️  PY_BIN(selected): $PY_BIN"

autostart_mac() {
  local plist="$HOME/Library/LaunchAgents/com.openclaw.wtt.autopoll.plist"
  mkdir -p "$HOME/Library/LaunchAgents"

  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.openclaw.wtt.autopoll</string>

    <key>ProgramArguments</key>
    <array>
      <string>$WRAPPER_SCRIPT</string>
    </array>

    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>

    <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>$SERVICE_PATH</string>
      <key>OPENCLAW_BIN</key>
      <string>$OPENCLAW_BIN</string>
      <key>WTT_SKILL_DIR</key>
      <string>$SKILL_ROOT</string>
      <key>WTT_PY_BIN</key>
      <string>$PY_BIN</string>
    </dict>

    <key>StandardOutPath</key>
    <string>/tmp/wtt_autopoll.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/wtt_autopoll_error.log</string>
  </dict>
</plist>
PLIST

  launchctl bootout "gui/$(id -u)/com.openclaw.wtt.autopoll" >/dev/null 2>&1 || true
  launchctl bootstrap "gui/$(id -u)" "$plist"
  launchctl kickstart -k "gui/$(id -u)/com.openclaw.wtt.autopoll"

  echo "✅ macOS launchd service installed"
  launchctl list | grep com.openclaw.wtt.autopoll || true
}

autostart_linux() {
  local unit_dir="$HOME/.config/systemd/user"
  local unit="$unit_dir/wtt-autopoll.service"
  mkdir -p "$unit_dir"

  cat > "$unit" <<UNIT
[Unit]
Description=OpenClaw WTT Auto Poll
After=network-online.target

[Service]
Type=simple
ExecStart=$WRAPPER_SCRIPT
Restart=always
RestartSec=2
Environment="PATH=$SERVICE_PATH"
Environment="OPENCLAW_BIN=$OPENCLAW_BIN"
Environment="HOME=$HOME"
Environment="WTT_SKILL_DIR=$SKILL_ROOT"
Environment="WTT_PY_BIN=$PY_BIN"
WorkingDirectory=$WORKDIR
StandardOutput=append:/tmp/wtt_autopoll.log
StandardError=append:/tmp/wtt_autopoll_error.log

[Install]
WantedBy=default.target
UNIT

  systemctl --user daemon-reload
  systemctl --user enable --now wtt-autopoll.service

  echo "✅ Linux systemd user service installed"
  systemctl --user status wtt-autopoll.service --no-pager || true
}

init_env_file
ensure_wrapper_script
ensure_python_deps

case "$(uname -s)" in
  Darwin)
    autostart_mac
    ;;
  Linux)
    autostart_linux
    ;;
  *)
    echo "❌ Unsupported OS: $(uname -s)"
    exit 1
    ;;
esac

echo "✅ WTT auto_poll autostart configured"